In [ ]:
###Datacamp intro to python Skills assessment Check 
##The questions are not my own work
#The answers and explanations are

In [1]:
##Which of the following returns 0.75?
#You can do this in your head of course, but this is python training. Printing each option returns each individual answer
print(5/8)
print(3/8)
print(6/8) #correct
print(7/8)

0.625
0.375
0.75
0.875


In [11]:
##Complete code to return output of (3,2)
#Method options are shape, len, size, dim

import numpy as np
numbers = [[50,3], [21,5], [32,80]]
np_array = np.array(numbers)
print(np_array.shape) #Answer
#np_array.shape returns the shape of the object. So here when used on this array, (3,2) means that there are 3 dimensions each containing 2 elements.

#print(np_array.len) # error numpy.ndarray object has no attribute len (length)
#print(np_array.size) # returns '6'. "Size" call indicates how many elements are in np array
#print(np_array.dim)# error numpy.ndarray object has no attribute dim

(3, 2)


In [12]:
##What will "np.array([True,1,2]) + np.array([3,4,False])" return?
#Yes this can be done in your head also because we know that True = 1 and False = 0 but that isn't Python-y.
#Answer should be array([4,5,2])

np.array([True,1,2]) + np.array([3,4,False]) #Yes, it is as above

array([4, 5, 2])

In [14]:
##Complete code to return output "Bob Smith"
#Options are: **, +, *
# ** is exponent, * is multiplication, so we want +

name = "Bob"
surname = " Smith"
print(name + surname)

Bob Smith


In [15]:
## Which of the following is true?

#1 General imports are preferred over selective imports
#2 Both general and selective imports are preferred
#3 Selective imports are preferred over general imports

#1 is the answer. This is preferred as it ensures that you are not missing a critical piece of functionality from the module/package you're working with. 

In [16]:
##Which of the follwing statements is true for boolean numpy arrays?

#1 Boolean numpy array is created when comparison is made between arrays of different shape
#2 Boolean numpy array is an array consisting of boolean values
#3 Boolean numpy array can't contain random boolean values
#4 Boolean numpy array can contain values of different data types

#2 is the answer. 

In [18]:
##What is the output of this code?
#The print statement is asking python to return the value of the 3rd dimension, 2nd element because python is 0 indexed. Answer should be '7'


import numpy as np
np_2d = np.array([[2,3],[4,5],[6,7]])
print(np_2d[2,1])

# dimension    0     1     2
# element     0 1   0 1   0 1
#          ([[2,3],[4,5],[6,7]])

7


In [19]:
##Which one of these is ture for 2D numpy arithmetic?

#1 Matrices are not able to perform all calculations element by element. #False
#2 Matrices can be combined with single numbers, with vectors, and with other matrices
#3 Matrices can not be combined with single numbers, with vectors, and with other matrices #False

#2 is the answer.

In [21]:
##Complete the code to return the output: ['Jan', 'Feb', 'Mar', 'July']

#options are 4, "Apr", 3, -2

# 4 is incorrect because that index does not exist in the list
# -2 is incorrect because it would return "Mar" to be changed not "Apr"
# "Apr" is incorrect because list indices must be integers or slices
# 3 is the answer 

x = ["Jan", "Feb", "Mar", "Apr"]
x[3] = "July"
print(x)

['Jan', 'Feb', 'Mar', 'July']


In [22]:
##What is the output of this code?

x = "r" #string
print(x + ' data')

# this should evaluate to "r data"

r data


In [23]:
##Which of the following would call the "x" method on the object p. 
#method calls are object.method()

#Answer is p.x()

In [24]:
##Complete the code to return the output
#Desired output: [15,15,14,9,65]

y = [15,15,14,9]
y.append(65)
print(y)

##The other two options for answers have correct syntax, but are instructing python to append the wrong number. This y.append(65) means to add the integer 65 to the end of the existing list object. 


[15, 15, 14, 9, 65]


In [25]:
##What does ndarray stand for?

#Answer n dimensional array because n can be any number.

In [26]:
##Which of the following accesses the first column of the np_2d 2D numpy array?

#First column would be the element at index 0 for all dimensions with an array. np_array[dimension, element]

#np_2d[:,0] ":" indicating all dimensions within the array, 0 indicating the first element or column for this example. 

In [27]:
##x and y are as follows: 

x = np.array([[1,2,7],
             [7,7,1]])
y = np.array([[6,5,5],
             [0,6,1]])

#what is the output?
print(x-y)

#This can be solved with matrix arithmetic and should be: [[-5 -3 2] [7 1 0]]

[[-5 -3  2]
 [ 7  1  0]]


In [33]:
##Select the code to return the output - there isn't output?
#This is not an error, we are looking for what returns an "empty return" so it is #3

#1
x=int(2.3) #evaluates to 2
y=0
print(x*float(y)) #returns 0.0 because 2 x 0.0

#2
x = int(True) #evaluates to 1
y = 1
print (x * bool(y)) #returns 1 because 1x1

#3
x = int(False) #evalues to 0
y = 1
print(x * str(y)) #evaluates to nothing because it is undefined or N/A

0.0
1



In [34]:
##What is a function

#1 A code template for creating objects
#2 A collection of modules  #No, that is a package
#3 A piece of reusable code

#3 is the answer

In [35]:
##What is the output of this code?

practice = ["Introduction", "Python", "DataCamp", "R", "SQL", "Data Science"]
x = -6
y = -3
print(practice[x:y])

#this is saying practice [-6:-3]. -6 index is "Introduction" counting from the end. -3 is "R". So the slice would be from -6 to -3 but not including "R"
#Answer should be [Introduction", "Python", "DataCamp"] and it is.

['Introduction', 'Python', 'DataCamp']


In [36]:
##Complete the code to return the output
#Desired output is [7]

#import numpy as np
#store = np.array(["X", "Z", "Z", "Z"])
#cost = np.array([7,1,9,4])
#select_cost = cost[store ==?]
#print(select_cost)

#Options:
#1 select_cost #doesn't make sense because reading right to left, select cost doesn't exist yet if placed in ?
#2 "Y" #No, not a valid answer because it doesn't exist in this problem
#3 "Z" #No because Z could be 1, 9, or 4
#4 "X" #Yes. The problem is asking for the element of cost based on the array in store. the first element in store is x, and would return the first element in cost if using that as an argument. 

import numpy as np
store = np.array(["X", "Z", "Z", "Z"])
cost = np.array([7,1,9,4])
select_cost = cost[store == "X"]
print(select_cost)

[7]


In [37]:
##What is the output of this code?

import numpy as np
np_2d = np.array([[1.5,6.4,7.8,2.2], [4.3,8.7,1.9,3.4], [5.3,7.3,9.4,2.5]])
np_2d[2:, 2:]

#The first 2: is indicating "dimension at index 2 of the array until the end", the second 2: is indicating the 
#"element at index 2 until the end."" So this should return array([[9.4, 2.5]]) and it does.

#Because:

# Dimension       0                  1                  2
# element   0   1   2   3      0   1   2   3      0   1   2   3
np.array([[1.5,6.4,7.8,2.2], [4.3,8.7,1.9,3.4], [5.3,7.3,9.4,2.5]])

array([[9.4, 2.5]])

In [38]:
##Select the code to return the output: 3.5
#np_2d[0,:] = dimension at index 0, all elements = [5,6,1,2,3,4]


#1
import numpy as np
np_2d = np.array([[5,6,1,2,3,4], [4,5,3,2,1,8], [9,10,3,7,6,5]])
print(np.median(np_2d[0,:]))
#median would re-order to 1,2,3,4,5,6 and median would be 3.5
#this is the answer

#2
#1
import numpy as np
np_2d = np.array([[5,6,1,2,3,4], [4,5,3,2,1,8], [9,10,3,7,6,5]])
print(np.sum(np_2d[0,:]))
#sum would be 21

#3
#1
import numpy as np
np_2d = np.array([[5,6,1,2,3,4], [4,5,3,2,1,8], [9,10,3,7,6,5]])
print(np.std(np_2d[0,:]))
#std would be standard deviation which should be 1.something

3.5
21
1.707825127659933


In [39]:
##What are the optional arguments to the function 'function_1()'?

#function_1(r1, q, p = None, r2 = None)

#the answer is p and r2

In [40]:
##Complete the code and return the output
#Desired output: [['i', 'x', 'y'], [0,0,3], [2.54, 9.2, 3.84]]

a = [2.54, 9.2, 3.84]
b = ['i', 'x', 'y']
c = [0,0,3]
#print(what?)
print([b,c,a])

[['i', 'x', 'y'], [0, 0, 3], [2.54, 9.2, 3.84]]


In [46]:
##Complete the code to return the output
#Desired output: 5.0

# Find the mean of the second column of costs
import numpy as np
costs = np.column_stack(([2, 1, 2, 1],
                        [4, 6, 5, 5]))
mean_costs = np.mean(costs[:,1])
print(mean_costs)

#If you call print(costs) you can see that each dimension in the array becomes a column instead of the other way around where corresponding elements between dimensions would become rows. 
#So there are two columns total. Each dimension corresponding to the data in the respective column. The mean of the elements in the second column = 5, but we have to properly select it because it has changed.
#print(costs) yields:
#[[2 4]
 #[1 6]
 #[2 5]
 #[1 5]]
    #Now, though it isn't a data frame, the slicing follows a [rows, columns] syntax. So the piece we want is [:,1] meaning all rows from column at index 1.


5.0


In [50]:
##Complete the code to return the output
#Desired output: 10

x = 5
y = x #so it is also equal to 5

print (x + y) #use + because * and ** would multiply and do exponent, respectively, instead

10


In [51]:
##Complete the code to return the output
#Desired output: 3.65

#Find the median of x
import numpy as np
x = np.array([4.19, 3.65, 2.93])
#print(what?(x)) # no multiple choice answers given. This was fill in the blank.
print(np.median(x))

3.65


In [58]:
##Complete the code to return the output
#Desired output: ['j', 'x', 'n', 'x']

#Choices
#del - this deletes the selection - this is the right answer
#replace - replaces with something else, that is not what is happening and it is not defined, so probably doesn't exist in this context
#rm - Not defined, probably does not exist as a function in python
#remove - Not defined, probably does not exist as a function in python
#cut - Not defined, probably does not exist as a function in python
#delete - Not defined, probably does not exist as a function in python

p = ['j', 'x', 'n', 'k', 'e', 'x']
#what(p[3:5])
del(p[3:5])
print(p)

['j', 'x', 'n', 'x']


In [69]:
##Complete the code to return the output
#Desired output: (2,4)

#Choices:
#dimensions - attribute does not exist
#size - tells the total number of elements across all dimensions
#shape - this is correct as this array contains two dimensions, each containing 4 elements. So (2,4)


import numpy as np
x = np.array([14, 21, 24, 24])
y = np.array([12, 6, 23, 29])
z = np.array([x,y])
#print(z.what?)
print(z.shape)

(2, 4)


In [70]:
##Complete the code to return the output
#Desired output: 2.266911751455907

#Choices:
#sum - obviously not correct here as the answer is a float barely larger than the 4th element in the object. Sum = 23
#median - re-write - 1,2,3,4,5,8 so answer is 3.5
#std - The answer

import numpy as np
np_2d = np.array([[5,6,1,2,3,4], [4,5,3,2,1,8], [9,10,3,7,6,5]])
#print(np.what?(np_2d[1,:]))
#slice indicates all elements of dimension at index 1
print(np.std(np_2d[1,:]))

2.266911751455907


In [72]:
##Complete the code to return the output
#Desired output: ['DataCamp', 'Python', 'Practice']

#Expected answer would be "1" as that is the element that contains the strings.

x = [[1,2,3,4,5], ['DataCamp', 'Python', 'Practice', 'Exercises'], [True, False, 0,1]]
print(x[0][:3])   #indicates first list object in main list
print(x[-1][:3])  #indicates the last list object in the main list
print(x[1][:3])   #Answer
print(x[3][:3])   #index doesn't exist in this context

[1, 2, 3]
[True, False, 0]
['DataCamp', 'Python', 'Practice']


IndexError: list index out of range